/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as ResetPasswordTokenImport } from './routes/reset-password.$token'
import { Route as AuthenticatedAdmUserRoleImport } from './routes/_authenticated/adm/user-role'
import { Route as AuthenticatedAdmRolePermissionImport } from './routes/_authenticated/adm/role-permission'
import { Route as AuthenticatedAdmRoleMenuImport } from './routes/_authenticated/adm/role-menu'
import { Route as AuthenticatedAdmApprovalStructureImport } from './routes/_authenticated/adm/approval-structure'
import { Route as AuthenticatedAdmActivityLogImport } from './routes/_authenticated/adm/activity-log'
import { Route as AuthenticatedPurMasterBillingTermImport } from './routes/_authenticated/pur/master/billing-term'
import { Route as AuthenticatedPrdMasterSubSectionImport } from './routes/_authenticated/prd/master/sub-section'
import { Route as AuthenticatedPrdMasterSectionImport } from './routes/_authenticated/prd/master/section'
import { Route as AuthenticatedPrdMasterFcsImport } from './routes/_authenticated/prd/master/fcs'
import { Route as AuthenticatedPrdMasterBuildingImport } from './routes/_authenticated/prd/master/building'
import { Route as AuthenticatedPidMasterWarehouseImport } from './routes/_authenticated/pid/master/warehouse'
import { Route as AuthenticatedMntMasterMachineImport } from './routes/_authenticated/mnt/master/machine'
import { Route as AuthenticatedMktMasterBillingTermImport } from './routes/_authenticated/mkt/master/billing-term'
import { Route as AuthenticatedEgdMasterUomImport } from './routes/_authenticated/egd/master/uom'
import { Route as AuthenticatedEgdMasterProcessImport } from './routes/_authenticated/egd/master/process'
import { Route as AuthenticatedAdmMasterUserImport } from './routes/_authenticated/adm/master/user'
import { Route as AuthenticatedAdmMasterRoleImport } from './routes/_authenticated/adm/master/role'
import { Route as AuthenticatedAdmMasterReasonImport } from './routes/_authenticated/adm/master/reason'
import { Route as AuthenticatedAdmMasterMenuImport } from './routes/_authenticated/adm/master/menu'
import { Route as AuthenticatedAdmMasterKeyValueImport } from './routes/_authenticated/adm/master/key-value'
import { Route as AuthenticatedAdmMasterItemCategoryImport } from './routes/_authenticated/adm/master/item-category'
import { Route as AuthenticatedAdmMasterEmployeeImport } from './routes/_authenticated/adm/master/employee'
import { Route as AuthenticatedAdmMasterDepartmentImport } from './routes/_authenticated/adm/master/department'
import { Route as AuthenticatedAcfMasterTaxCodeImport } from './routes/_authenticated/acf/master/tax-code'
import { Route as AuthenticatedAcfMasterCurrencyImport } from './routes/_authenticated/acf/master/currency'
import { Route as AuthenticatedAcfMasterChartOfAccountImport } from './routes/_authenticated/acf/master/chart-of-account'
import { Route as AuthenticatedAcfMasterBankImport } from './routes/_authenticated/acf/master/bank'
import { Route as AuthenticatedGeneralMasterItemRawMaterialSurfaceFinishingImport } from './routes/_authenticated/general/master/item/raw-material/surface-finishing'
import { Route as AuthenticatedGeneralMasterItemRawMaterialSourcingImport } from './routes/_authenticated/general/master/item/raw-material/sourcing'
import { Route as AuthenticatedGeneralMasterItemRawMaterialProductImport } from './routes/_authenticated/general/master/item/raw-material/product'
import { Route as AuthenticatedGeneralMasterItemRawMaterialProcessingImport } from './routes/_authenticated/general/master/item/raw-material/processing'
import { Route as AuthenticatedGeneralMasterItemRawMaterialGroupImport } from './routes/_authenticated/general/master/item/raw-material/group'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const ResetPasswordTokenRoute = ResetPasswordTokenImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedAdmUserRoleRoute = AuthenticatedAdmUserRoleImport.update({
  id: '/adm/user-role',
  path: '/adm/user-role',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAdmRolePermissionRoute =
  AuthenticatedAdmRolePermissionImport.update({
    id: '/adm/role-permission',
    path: '/adm/role-permission',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdmRoleMenuRoute = AuthenticatedAdmRoleMenuImport.update({
  id: '/adm/role-menu',
  path: '/adm/role-menu',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAdmApprovalStructureRoute =
  AuthenticatedAdmApprovalStructureImport.update({
    id: '/adm/approval-structure',
    path: '/adm/approval-structure',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdmActivityLogRoute =
  AuthenticatedAdmActivityLogImport.update({
    id: '/adm/activity-log',
    path: '/adm/activity-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPurMasterBillingTermRoute =
  AuthenticatedPurMasterBillingTermImport.update({
    id: '/pur/master/billing-term',
    path: '/pur/master/billing-term',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPrdMasterSubSectionRoute =
  AuthenticatedPrdMasterSubSectionImport.update({
    id: '/prd/master/sub-section',
    path: '/prd/master/sub-section',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPrdMasterSectionRoute =
  AuthenticatedPrdMasterSectionImport.update({
    id: '/prd/master/section',
    path: '/prd/master/section',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPrdMasterFcsRoute = AuthenticatedPrdMasterFcsImport.update({
  id: '/prd/master/fcs',
  path: '/prd/master/fcs',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedPrdMasterBuildingRoute =
  AuthenticatedPrdMasterBuildingImport.update({
    id: '/prd/master/building',
    path: '/prd/master/building',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPidMasterWarehouseRoute =
  AuthenticatedPidMasterWarehouseImport.update({
    id: '/pid/master/warehouse',
    path: '/pid/master/warehouse',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedMntMasterMachineRoute =
  AuthenticatedMntMasterMachineImport.update({
    id: '/mnt/master/machine',
    path: '/mnt/master/machine',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedMktMasterBillingTermRoute =
  AuthenticatedMktMasterBillingTermImport.update({
    id: '/mkt/master/billing-term',
    path: '/mkt/master/billing-term',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedEgdMasterUomRoute = AuthenticatedEgdMasterUomImport.update({
  id: '/egd/master/uom',
  path: '/egd/master/uom',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedEgdMasterProcessRoute =
  AuthenticatedEgdMasterProcessImport.update({
    id: '/egd/master/process',
    path: '/egd/master/process',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdmMasterUserRoute = AuthenticatedAdmMasterUserImport.update(
  {
    id: '/adm/master/user',
    path: '/adm/master/user',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedAdmMasterRoleRoute = AuthenticatedAdmMasterRoleImport.update(
  {
    id: '/adm/master/role',
    path: '/adm/master/role',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedAdmMasterReasonRoute =
  AuthenticatedAdmMasterReasonImport.update({
    id: '/adm/master/reason',
    path: '/adm/master/reason',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdmMasterMenuRoute = AuthenticatedAdmMasterMenuImport.update(
  {
    id: '/adm/master/menu',
    path: '/adm/master/menu',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedAdmMasterKeyValueRoute =
  AuthenticatedAdmMasterKeyValueImport.update({
    id: '/adm/master/key-value',
    path: '/adm/master/key-value',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdmMasterItemCategoryRoute =
  AuthenticatedAdmMasterItemCategoryImport.update({
    id: '/adm/master/item-category',
    path: '/adm/master/item-category',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdmMasterEmployeeRoute =
  AuthenticatedAdmMasterEmployeeImport.update({
    id: '/adm/master/employee',
    path: '/adm/master/employee',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAdmMasterDepartmentRoute =
  AuthenticatedAdmMasterDepartmentImport.update({
    id: '/adm/master/department',
    path: '/adm/master/department',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAcfMasterTaxCodeRoute =
  AuthenticatedAcfMasterTaxCodeImport.update({
    id: '/acf/master/tax-code',
    path: '/acf/master/tax-code',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAcfMasterCurrencyRoute =
  AuthenticatedAcfMasterCurrencyImport.update({
    id: '/acf/master/currency',
    path: '/acf/master/currency',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAcfMasterChartOfAccountRoute =
  AuthenticatedAcfMasterChartOfAccountImport.update({
    id: '/acf/master/chart-of-account',
    path: '/acf/master/chart-of-account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAcfMasterBankRoute = AuthenticatedAcfMasterBankImport.update(
  {
    id: '/acf/master/bank',
    path: '/acf/master/bank',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedGeneralMasterItemRawMaterialSurfaceFinishingRoute =
  AuthenticatedGeneralMasterItemRawMaterialSurfaceFinishingImport.update({
    id: '/general/master/item/raw-material/surface-finishing',
    path: '/general/master/item/raw-material/surface-finishing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedGeneralMasterItemRawMaterialSourcingRoute =
  AuthenticatedGeneralMasterItemRawMaterialSourcingImport.update({
    id: '/general/master/item/raw-material/sourcing',
    path: '/general/master/item/raw-material/sourcing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedGeneralMasterItemRawMaterialProductRoute =
  AuthenticatedGeneralMasterItemRawMaterialProductImport.update({
    id: '/general/master/item/raw-material/product',
    path: '/general/master/item/raw-material/product',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedGeneralMasterItemRawMaterialProcessingRoute =
  AuthenticatedGeneralMasterItemRawMaterialProcessingImport.update({
    id: '/general/master/item/raw-material/processing',
    path: '/general/master/item/raw-material/processing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedGeneralMasterItemRawMaterialGroupRoute =
  AuthenticatedGeneralMasterItemRawMaterialGroupImport.update({
    id: '/general/master/item/raw-material/group',
    path: '/general/master/item/raw-material/group',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/adm/activity-log': {
      id: '/_authenticated/adm/activity-log'
      path: '/adm/activity-log'
      fullPath: '/adm/activity-log'
      preLoaderRoute: typeof AuthenticatedAdmActivityLogImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/adm/approval-structure': {
      id: '/_authenticated/adm/approval-structure'
      path: '/adm/approval-structure'
      fullPath: '/adm/approval-structure'
      preLoaderRoute: typeof AuthenticatedAdmApprovalStructureImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/adm/role-menu': {
      id: '/_authenticated/adm/role-menu'
      path: '/adm/role-menu'
      fullPath: '/adm/role-menu'
      preLoaderRoute: typeof AuthenticatedAdmRoleMenuImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/adm/role-permission': {
      id: '/_authenticated/adm/role-permission'
      path: '/adm/role-permission'
      fullPath: '/adm/role-permission'
      preLoaderRoute: typeof AuthenticatedAdmRolePermissionImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/adm/user-role': {
      id: '/_authenticated/adm/user-role'
      path: '/adm/user-role'
      fullPath: '/adm/user-role'
      preLoaderRoute: typeof AuthenticatedAdmUserRoleImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/acf/master/bank': {
      id: '/_authenticated/acf/master/bank'
      path: '/acf/master/bank'
      fullPath: '/acf/master/bank'
      preLoaderRoute: typeof AuthenticatedAcfMasterBankImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/acf/master/chart-of-account': {
      id: '/_authenticated/acf/master/chart-of-account'
      path: '/acf/master/chart-of-account'
      fullPath: '/acf/master/chart-of-account'
      preLoaderRoute: typeof AuthenticatedAcfMasterChartOfAccountImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/acf/master/currency': {
      id: '/_authenticated/acf/master/currency'
      path: '/acf/master/currency'
      fullPath: '/acf/master/currency'
      preLoaderRoute: typeof AuthenticatedAcfMasterCurrencyImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/acf/master/tax-code': {
      id: '/_authenticated/acf/master/tax-code'
      path: '/acf/master/tax-code'
      fullPath: '/acf/master/tax-code'
      preLoaderRoute: typeof AuthenticatedAcfMasterTaxCodeImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/adm/master/department': {
      id: '/_authenticated/adm/master/department'
      path: '/adm/master/department'
      fullPath: '/adm/master/department'
      preLoaderRoute: typeof AuthenticatedAdmMasterDepartmentImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/adm/master/employee': {
      id: '/_authenticated/adm/master/employee'
      path: '/adm/master/employee'
      fullPath: '/adm/master/employee'
      preLoaderRoute: typeof AuthenticatedAdmMasterEmployeeImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/adm/master/item-category': {
      id: '/_authenticated/adm/master/item-category'
      path: '/adm/master/item-category'
      fullPath: '/adm/master/item-category'
      preLoaderRoute: typeof AuthenticatedAdmMasterItemCategoryImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/adm/master/key-value': {
      id: '/_authenticated/adm/master/key-value'
      path: '/adm/master/key-value'
      fullPath: '/adm/master/key-value'
      preLoaderRoute: typeof AuthenticatedAdmMasterKeyValueImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/adm/master/menu': {
      id: '/_authenticated/adm/master/menu'
      path: '/adm/master/menu'
      fullPath: '/adm/master/menu'
      preLoaderRoute: typeof AuthenticatedAdmMasterMenuImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/adm/master/reason': {
      id: '/_authenticated/adm/master/reason'
      path: '/adm/master/reason'
      fullPath: '/adm/master/reason'
      preLoaderRoute: typeof AuthenticatedAdmMasterReasonImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/adm/master/role': {
      id: '/_authenticated/adm/master/role'
      path: '/adm/master/role'
      fullPath: '/adm/master/role'
      preLoaderRoute: typeof AuthenticatedAdmMasterRoleImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/adm/master/user': {
      id: '/_authenticated/adm/master/user'
      path: '/adm/master/user'
      fullPath: '/adm/master/user'
      preLoaderRoute: typeof AuthenticatedAdmMasterUserImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/egd/master/process': {
      id: '/_authenticated/egd/master/process'
      path: '/egd/master/process'
      fullPath: '/egd/master/process'
      preLoaderRoute: typeof AuthenticatedEgdMasterProcessImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/egd/master/uom': {
      id: '/_authenticated/egd/master/uom'
      path: '/egd/master/uom'
      fullPath: '/egd/master/uom'
      preLoaderRoute: typeof AuthenticatedEgdMasterUomImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/mkt/master/billing-term': {
      id: '/_authenticated/mkt/master/billing-term'
      path: '/mkt/master/billing-term'
      fullPath: '/mkt/master/billing-term'
      preLoaderRoute: typeof AuthenticatedMktMasterBillingTermImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/mnt/master/machine': {
      id: '/_authenticated/mnt/master/machine'
      path: '/mnt/master/machine'
      fullPath: '/mnt/master/machine'
      preLoaderRoute: typeof AuthenticatedMntMasterMachineImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/pid/master/warehouse': {
      id: '/_authenticated/pid/master/warehouse'
      path: '/pid/master/warehouse'
      fullPath: '/pid/master/warehouse'
      preLoaderRoute: typeof AuthenticatedPidMasterWarehouseImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/prd/master/building': {
      id: '/_authenticated/prd/master/building'
      path: '/prd/master/building'
      fullPath: '/prd/master/building'
      preLoaderRoute: typeof AuthenticatedPrdMasterBuildingImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/prd/master/fcs': {
      id: '/_authenticated/prd/master/fcs'
      path: '/prd/master/fcs'
      fullPath: '/prd/master/fcs'
      preLoaderRoute: typeof AuthenticatedPrdMasterFcsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/prd/master/section': {
      id: '/_authenticated/prd/master/section'
      path: '/prd/master/section'
      fullPath: '/prd/master/section'
      preLoaderRoute: typeof AuthenticatedPrdMasterSectionImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/prd/master/sub-section': {
      id: '/_authenticated/prd/master/sub-section'
      path: '/prd/master/sub-section'
      fullPath: '/prd/master/sub-section'
      preLoaderRoute: typeof AuthenticatedPrdMasterSubSectionImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/pur/master/billing-term': {
      id: '/_authenticated/pur/master/billing-term'
      path: '/pur/master/billing-term'
      fullPath: '/pur/master/billing-term'
      preLoaderRoute: typeof AuthenticatedPurMasterBillingTermImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/general/master/item/raw-material/group': {
      id: '/_authenticated/general/master/item/raw-material/group'
      path: '/general/master/item/raw-material/group'
      fullPath: '/general/master/item/raw-material/group'
      preLoaderRoute: typeof AuthenticatedGeneralMasterItemRawMaterialGroupImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/general/master/item/raw-material/processing': {
      id: '/_authenticated/general/master/item/raw-material/processing'
      path: '/general/master/item/raw-material/processing'
      fullPath: '/general/master/item/raw-material/processing'
      preLoaderRoute: typeof AuthenticatedGeneralMasterItemRawMaterialProcessingImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/general/master/item/raw-material/product': {
      id: '/_authenticated/general/master/item/raw-material/product'
      path: '/general/master/item/raw-material/product'
      fullPath: '/general/master/item/raw-material/product'
      preLoaderRoute: typeof AuthenticatedGeneralMasterItemRawMaterialProductImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/general/master/item/raw-material/sourcing': {
      id: '/_authenticated/general/master/item/raw-material/sourcing'
      path: '/general/master/item/raw-material/sourcing'
      fullPath: '/general/master/item/raw-material/sourcing'
      preLoaderRoute: typeof AuthenticatedGeneralMasterItemRawMaterialSourcingImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/general/master/item/raw-material/surface-finishing': {
      id: '/_authenticated/general/master/item/raw-material/surface-finishing'
      path: '/general/master/item/raw-material/surface-finishing'
      fullPath: '/general/master/item/raw-material/surface-finishing'
      preLoaderRoute: typeof AuthenticatedGeneralMasterItemRawMaterialSurfaceFinishingImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdmActivityLogRoute: typeof AuthenticatedAdmActivityLogRoute
  AuthenticatedAdmApprovalStructureRoute: typeof AuthenticatedAdmApprovalStructureRoute
  AuthenticatedAdmRoleMenuRoute: typeof AuthenticatedAdmRoleMenuRoute
  AuthenticatedAdmRolePermissionRoute: typeof AuthenticatedAdmRolePermissionRoute
  AuthenticatedAdmUserRoleRoute: typeof AuthenticatedAdmUserRoleRoute
  AuthenticatedAcfMasterBankRoute: typeof AuthenticatedAcfMasterBankRoute
  AuthenticatedAcfMasterChartOfAccountRoute: typeof AuthenticatedAcfMasterChartOfAccountRoute
  AuthenticatedAcfMasterCurrencyRoute: typeof AuthenticatedAcfMasterCurrencyRoute
  AuthenticatedAcfMasterTaxCodeRoute: typeof AuthenticatedAcfMasterTaxCodeRoute
  AuthenticatedAdmMasterDepartmentRoute: typeof AuthenticatedAdmMasterDepartmentRoute
  AuthenticatedAdmMasterEmployeeRoute: typeof AuthenticatedAdmMasterEmployeeRoute
  AuthenticatedAdmMasterItemCategoryRoute: typeof AuthenticatedAdmMasterItemCategoryRoute
  AuthenticatedAdmMasterKeyValueRoute: typeof AuthenticatedAdmMasterKeyValueRoute
  AuthenticatedAdmMasterMenuRoute: typeof AuthenticatedAdmMasterMenuRoute
  AuthenticatedAdmMasterReasonRoute: typeof AuthenticatedAdmMasterReasonRoute
  AuthenticatedAdmMasterRoleRoute: typeof AuthenticatedAdmMasterRoleRoute
  AuthenticatedAdmMasterUserRoute: typeof AuthenticatedAdmMasterUserRoute
  AuthenticatedEgdMasterProcessRoute: typeof AuthenticatedEgdMasterProcessRoute
  AuthenticatedEgdMasterUomRoute: typeof AuthenticatedEgdMasterUomRoute
  AuthenticatedMktMasterBillingTermRoute: typeof AuthenticatedMktMasterBillingTermRoute
  AuthenticatedMntMasterMachineRoute: typeof AuthenticatedMntMasterMachineRoute
  AuthenticatedPidMasterWarehouseRoute: typeof AuthenticatedPidMasterWarehouseRoute
  AuthenticatedPrdMasterBuildingRoute: typeof AuthenticatedPrdMasterBuildingRoute
  AuthenticatedPrdMasterFcsRoute: typeof AuthenticatedPrdMasterFcsRoute
  AuthenticatedPrdMasterSectionRoute: typeof AuthenticatedPrdMasterSectionRoute
  AuthenticatedPrdMasterSubSectionRoute: typeof AuthenticatedPrdMasterSubSectionRoute
  AuthenticatedPurMasterBillingTermRoute: typeof AuthenticatedPurMasterBillingTermRoute
  AuthenticatedGeneralMasterItemRawMaterialGroupRoute: typeof AuthenticatedGeneralMasterItemRawMaterialGroupRoute
  AuthenticatedGeneralMasterItemRawMaterialProcessingRoute: typeof AuthenticatedGeneralMasterItemRawMaterialProcessingRoute
  AuthenticatedGeneralMasterItemRawMaterialProductRoute: typeof AuthenticatedGeneralMasterItemRawMaterialProductRoute
  AuthenticatedGeneralMasterItemRawMaterialSourcingRoute: typeof AuthenticatedGeneralMasterItemRawMaterialSourcingRoute
  AuthenticatedGeneralMasterItemRawMaterialSurfaceFinishingRoute: typeof AuthenticatedGeneralMasterItemRawMaterialSurfaceFinishingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdmActivityLogRoute: AuthenticatedAdmActivityLogRoute,
  AuthenticatedAdmApprovalStructureRoute:
    AuthenticatedAdmApprovalStructureRoute,
  AuthenticatedAdmRoleMenuRoute: AuthenticatedAdmRoleMenuRoute,
  AuthenticatedAdmRolePermissionRoute: AuthenticatedAdmRolePermissionRoute,
  AuthenticatedAdmUserRoleRoute: AuthenticatedAdmUserRoleRoute,
  AuthenticatedAcfMasterBankRoute: AuthenticatedAcfMasterBankRoute,
  AuthenticatedAcfMasterChartOfAccountRoute:
    AuthenticatedAcfMasterChartOfAccountRoute,
  AuthenticatedAcfMasterCurrencyRoute: AuthenticatedAcfMasterCurrencyRoute,
  AuthenticatedAcfMasterTaxCodeRoute: AuthenticatedAcfMasterTaxCodeRoute,
  AuthenticatedAdmMasterDepartmentRoute: AuthenticatedAdmMasterDepartmentRoute,
  AuthenticatedAdmMasterEmployeeRoute: AuthenticatedAdmMasterEmployeeRoute,
  AuthenticatedAdmMasterItemCategoryRoute:
    AuthenticatedAdmMasterItemCategoryRoute,
  AuthenticatedAdmMasterKeyValueRoute: AuthenticatedAdmMasterKeyValueRoute,
  AuthenticatedAdmMasterMenuRoute: AuthenticatedAdmMasterMenuRoute,
  AuthenticatedAdmMasterReasonRoute: AuthenticatedAdmMasterReasonRoute,
  AuthenticatedAdmMasterRoleRoute: AuthenticatedAdmMasterRoleRoute,
  AuthenticatedAdmMasterUserRoute: AuthenticatedAdmMasterUserRoute,
  AuthenticatedEgdMasterProcessRoute: AuthenticatedEgdMasterProcessRoute,
  AuthenticatedEgdMasterUomRoute: AuthenticatedEgdMasterUomRoute,
  AuthenticatedMktMasterBillingTermRoute:
    AuthenticatedMktMasterBillingTermRoute,
  AuthenticatedMntMasterMachineRoute: AuthenticatedMntMasterMachineRoute,
  AuthenticatedPidMasterWarehouseRoute: AuthenticatedPidMasterWarehouseRoute,
  AuthenticatedPrdMasterBuildingRoute: AuthenticatedPrdMasterBuildingRoute,
  AuthenticatedPrdMasterFcsRoute: AuthenticatedPrdMasterFcsRoute,
  AuthenticatedPrdMasterSectionRoute: AuthenticatedPrdMasterSectionRoute,
  AuthenticatedPrdMasterSubSectionRoute: AuthenticatedPrdMasterSubSectionRoute,
  AuthenticatedPurMasterBillingTermRoute:
    AuthenticatedPurMasterBillingTermRoute,
  AuthenticatedGeneralMasterItemRawMaterialGroupRoute:
    AuthenticatedGeneralMasterItemRawMaterialGroupRoute,
  AuthenticatedGeneralMasterItemRawMaterialProcessingRoute:
    AuthenticatedGeneralMasterItemRawMaterialProcessingRoute,
  AuthenticatedGeneralMasterItemRawMaterialProductRoute:
    AuthenticatedGeneralMasterItemRawMaterialProductRoute,
  AuthenticatedGeneralMasterItemRawMaterialSourcingRoute:
    AuthenticatedGeneralMasterItemRawMaterialSourcingRoute,
  AuthenticatedGeneralMasterItemRawMaterialSurfaceFinishingRoute:
    AuthenticatedGeneralMasterItemRawMaterialSurfaceFinishingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/adm/activity-log': typeof AuthenticatedAdmActivityLogRoute
  '/adm/approval-structure': typeof AuthenticatedAdmApprovalStructureRoute
  '/adm/role-menu': typeof AuthenticatedAdmRoleMenuRoute
  '/adm/role-permission': typeof AuthenticatedAdmRolePermissionRoute
  '/adm/user-role': typeof AuthenticatedAdmUserRoleRoute
  '/acf/master/bank': typeof AuthenticatedAcfMasterBankRoute
  '/acf/master/chart-of-account': typeof AuthenticatedAcfMasterChartOfAccountRoute
  '/acf/master/currency': typeof AuthenticatedAcfMasterCurrencyRoute
  '/acf/master/tax-code': typeof AuthenticatedAcfMasterTaxCodeRoute
  '/adm/master/department': typeof AuthenticatedAdmMasterDepartmentRoute
  '/adm/master/employee': typeof AuthenticatedAdmMasterEmployeeRoute
  '/adm/master/item-category': typeof AuthenticatedAdmMasterItemCategoryRoute
  '/adm/master/key-value': typeof AuthenticatedAdmMasterKeyValueRoute
  '/adm/master/menu': typeof AuthenticatedAdmMasterMenuRoute
  '/adm/master/reason': typeof AuthenticatedAdmMasterReasonRoute
  '/adm/master/role': typeof AuthenticatedAdmMasterRoleRoute
  '/adm/master/user': typeof AuthenticatedAdmMasterUserRoute
  '/egd/master/process': typeof AuthenticatedEgdMasterProcessRoute
  '/egd/master/uom': typeof AuthenticatedEgdMasterUomRoute
  '/mkt/master/billing-term': typeof AuthenticatedMktMasterBillingTermRoute
  '/mnt/master/machine': typeof AuthenticatedMntMasterMachineRoute
  '/pid/master/warehouse': typeof AuthenticatedPidMasterWarehouseRoute
  '/prd/master/building': typeof AuthenticatedPrdMasterBuildingRoute
  '/prd/master/fcs': typeof AuthenticatedPrdMasterFcsRoute
  '/prd/master/section': typeof AuthenticatedPrdMasterSectionRoute
  '/prd/master/sub-section': typeof AuthenticatedPrdMasterSubSectionRoute
  '/pur/master/billing-term': typeof AuthenticatedPurMasterBillingTermRoute
  '/general/master/item/raw-material/group': typeof AuthenticatedGeneralMasterItemRawMaterialGroupRoute
  '/general/master/item/raw-material/processing': typeof AuthenticatedGeneralMasterItemRawMaterialProcessingRoute
  '/general/master/item/raw-material/product': typeof AuthenticatedGeneralMasterItemRawMaterialProductRoute
  '/general/master/item/raw-material/sourcing': typeof AuthenticatedGeneralMasterItemRawMaterialSourcingRoute
  '/general/master/item/raw-material/surface-finishing': typeof AuthenticatedGeneralMasterItemRawMaterialSurfaceFinishingRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/adm/activity-log': typeof AuthenticatedAdmActivityLogRoute
  '/adm/approval-structure': typeof AuthenticatedAdmApprovalStructureRoute
  '/adm/role-menu': typeof AuthenticatedAdmRoleMenuRoute
  '/adm/role-permission': typeof AuthenticatedAdmRolePermissionRoute
  '/adm/user-role': typeof AuthenticatedAdmUserRoleRoute
  '/acf/master/bank': typeof AuthenticatedAcfMasterBankRoute
  '/acf/master/chart-of-account': typeof AuthenticatedAcfMasterChartOfAccountRoute
  '/acf/master/currency': typeof AuthenticatedAcfMasterCurrencyRoute
  '/acf/master/tax-code': typeof AuthenticatedAcfMasterTaxCodeRoute
  '/adm/master/department': typeof AuthenticatedAdmMasterDepartmentRoute
  '/adm/master/employee': typeof AuthenticatedAdmMasterEmployeeRoute
  '/adm/master/item-category': typeof AuthenticatedAdmMasterItemCategoryRoute
  '/adm/master/key-value': typeof AuthenticatedAdmMasterKeyValueRoute
  '/adm/master/menu': typeof AuthenticatedAdmMasterMenuRoute
  '/adm/master/reason': typeof AuthenticatedAdmMasterReasonRoute
  '/adm/master/role': typeof AuthenticatedAdmMasterRoleRoute
  '/adm/master/user': typeof AuthenticatedAdmMasterUserRoute
  '/egd/master/process': typeof AuthenticatedEgdMasterProcessRoute
  '/egd/master/uom': typeof AuthenticatedEgdMasterUomRoute
  '/mkt/master/billing-term': typeof AuthenticatedMktMasterBillingTermRoute
  '/mnt/master/machine': typeof AuthenticatedMntMasterMachineRoute
  '/pid/master/warehouse': typeof AuthenticatedPidMasterWarehouseRoute
  '/prd/master/building': typeof AuthenticatedPrdMasterBuildingRoute
  '/prd/master/fcs': typeof AuthenticatedPrdMasterFcsRoute
  '/prd/master/section': typeof AuthenticatedPrdMasterSectionRoute
  '/prd/master/sub-section': typeof AuthenticatedPrdMasterSubSectionRoute
  '/pur/master/billing-term': typeof AuthenticatedPurMasterBillingTermRoute
  '/general/master/item/raw-material/group': typeof AuthenticatedGeneralMasterItemRawMaterialGroupRoute
  '/general/master/item/raw-material/processing': typeof AuthenticatedGeneralMasterItemRawMaterialProcessingRoute
  '/general/master/item/raw-material/product': typeof AuthenticatedGeneralMasterItemRawMaterialProductRoute
  '/general/master/item/raw-material/sourcing': typeof AuthenticatedGeneralMasterItemRawMaterialSourcingRoute
  '/general/master/item/raw-material/surface-finishing': typeof AuthenticatedGeneralMasterItemRawMaterialSurfaceFinishingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/adm/activity-log': typeof AuthenticatedAdmActivityLogRoute
  '/_authenticated/adm/approval-structure': typeof AuthenticatedAdmApprovalStructureRoute
  '/_authenticated/adm/role-menu': typeof AuthenticatedAdmRoleMenuRoute
  '/_authenticated/adm/role-permission': typeof AuthenticatedAdmRolePermissionRoute
  '/_authenticated/adm/user-role': typeof AuthenticatedAdmUserRoleRoute
  '/_authenticated/acf/master/bank': typeof AuthenticatedAcfMasterBankRoute
  '/_authenticated/acf/master/chart-of-account': typeof AuthenticatedAcfMasterChartOfAccountRoute
  '/_authenticated/acf/master/currency': typeof AuthenticatedAcfMasterCurrencyRoute
  '/_authenticated/acf/master/tax-code': typeof AuthenticatedAcfMasterTaxCodeRoute
  '/_authenticated/adm/master/department': typeof AuthenticatedAdmMasterDepartmentRoute
  '/_authenticated/adm/master/employee': typeof AuthenticatedAdmMasterEmployeeRoute
  '/_authenticated/adm/master/item-category': typeof AuthenticatedAdmMasterItemCategoryRoute
  '/_authenticated/adm/master/key-value': typeof AuthenticatedAdmMasterKeyValueRoute
  '/_authenticated/adm/master/menu': typeof AuthenticatedAdmMasterMenuRoute
  '/_authenticated/adm/master/reason': typeof AuthenticatedAdmMasterReasonRoute
  '/_authenticated/adm/master/role': typeof AuthenticatedAdmMasterRoleRoute
  '/_authenticated/adm/master/user': typeof AuthenticatedAdmMasterUserRoute
  '/_authenticated/egd/master/process': typeof AuthenticatedEgdMasterProcessRoute
  '/_authenticated/egd/master/uom': typeof AuthenticatedEgdMasterUomRoute
  '/_authenticated/mkt/master/billing-term': typeof AuthenticatedMktMasterBillingTermRoute
  '/_authenticated/mnt/master/machine': typeof AuthenticatedMntMasterMachineRoute
  '/_authenticated/pid/master/warehouse': typeof AuthenticatedPidMasterWarehouseRoute
  '/_authenticated/prd/master/building': typeof AuthenticatedPrdMasterBuildingRoute
  '/_authenticated/prd/master/fcs': typeof AuthenticatedPrdMasterFcsRoute
  '/_authenticated/prd/master/section': typeof AuthenticatedPrdMasterSectionRoute
  '/_authenticated/prd/master/sub-section': typeof AuthenticatedPrdMasterSubSectionRoute
  '/_authenticated/pur/master/billing-term': typeof AuthenticatedPurMasterBillingTermRoute
  '/_authenticated/general/master/item/raw-material/group': typeof AuthenticatedGeneralMasterItemRawMaterialGroupRoute
  '/_authenticated/general/master/item/raw-material/processing': typeof AuthenticatedGeneralMasterItemRawMaterialProcessingRoute
  '/_authenticated/general/master/item/raw-material/product': typeof AuthenticatedGeneralMasterItemRawMaterialProductRoute
  '/_authenticated/general/master/item/raw-material/sourcing': typeof AuthenticatedGeneralMasterItemRawMaterialSourcingRoute
  '/_authenticated/general/master/item/raw-material/surface-finishing': typeof AuthenticatedGeneralMasterItemRawMaterialSurfaceFinishingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/reset-password/$token'
    | '/'
    | '/adm/activity-log'
    | '/adm/approval-structure'
    | '/adm/role-menu'
    | '/adm/role-permission'
    | '/adm/user-role'
    | '/acf/master/bank'
    | '/acf/master/chart-of-account'
    | '/acf/master/currency'
    | '/acf/master/tax-code'
    | '/adm/master/department'
    | '/adm/master/employee'
    | '/adm/master/item-category'
    | '/adm/master/key-value'
    | '/adm/master/menu'
    | '/adm/master/reason'
    | '/adm/master/role'
    | '/adm/master/user'
    | '/egd/master/process'
    | '/egd/master/uom'
    | '/mkt/master/billing-term'
    | '/mnt/master/machine'
    | '/pid/master/warehouse'
    | '/prd/master/building'
    | '/prd/master/fcs'
    | '/prd/master/section'
    | '/prd/master/sub-section'
    | '/pur/master/billing-term'
    | '/general/master/item/raw-material/group'
    | '/general/master/item/raw-material/processing'
    | '/general/master/item/raw-material/product'
    | '/general/master/item/raw-material/sourcing'
    | '/general/master/item/raw-material/surface-finishing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password/$token'
    | '/'
    | '/adm/activity-log'
    | '/adm/approval-structure'
    | '/adm/role-menu'
    | '/adm/role-permission'
    | '/adm/user-role'
    | '/acf/master/bank'
    | '/acf/master/chart-of-account'
    | '/acf/master/currency'
    | '/acf/master/tax-code'
    | '/adm/master/department'
    | '/adm/master/employee'
    | '/adm/master/item-category'
    | '/adm/master/key-value'
    | '/adm/master/menu'
    | '/adm/master/reason'
    | '/adm/master/role'
    | '/adm/master/user'
    | '/egd/master/process'
    | '/egd/master/uom'
    | '/mkt/master/billing-term'
    | '/mnt/master/machine'
    | '/pid/master/warehouse'
    | '/prd/master/building'
    | '/prd/master/fcs'
    | '/prd/master/section'
    | '/prd/master/sub-section'
    | '/pur/master/billing-term'
    | '/general/master/item/raw-material/group'
    | '/general/master/item/raw-material/processing'
    | '/general/master/item/raw-material/product'
    | '/general/master/item/raw-material/sourcing'
    | '/general/master/item/raw-material/surface-finishing'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password/$token'
    | '/_authenticated/'
    | '/_authenticated/adm/activity-log'
    | '/_authenticated/adm/approval-structure'
    | '/_authenticated/adm/role-menu'
    | '/_authenticated/adm/role-permission'
    | '/_authenticated/adm/user-role'
    | '/_authenticated/acf/master/bank'
    | '/_authenticated/acf/master/chart-of-account'
    | '/_authenticated/acf/master/currency'
    | '/_authenticated/acf/master/tax-code'
    | '/_authenticated/adm/master/department'
    | '/_authenticated/adm/master/employee'
    | '/_authenticated/adm/master/item-category'
    | '/_authenticated/adm/master/key-value'
    | '/_authenticated/adm/master/menu'
    | '/_authenticated/adm/master/reason'
    | '/_authenticated/adm/master/role'
    | '/_authenticated/adm/master/user'
    | '/_authenticated/egd/master/process'
    | '/_authenticated/egd/master/uom'
    | '/_authenticated/mkt/master/billing-term'
    | '/_authenticated/mnt/master/machine'
    | '/_authenticated/pid/master/warehouse'
    | '/_authenticated/prd/master/building'
    | '/_authenticated/prd/master/fcs'
    | '/_authenticated/prd/master/section'
    | '/_authenticated/prd/master/sub-section'
    | '/_authenticated/pur/master/billing-term'
    | '/_authenticated/general/master/item/raw-material/group'
    | '/_authenticated/general/master/item/raw-material/processing'
    | '/_authenticated/general/master/item/raw-material/product'
    | '/_authenticated/general/master/item/raw-material/sourcing'
    | '/_authenticated/general/master/item/raw-material/surface-finishing'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/login",
        "/reset-password/$token"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/",
        "/_authenticated/adm/activity-log",
        "/_authenticated/adm/approval-structure",
        "/_authenticated/adm/role-menu",
        "/_authenticated/adm/role-permission",
        "/_authenticated/adm/user-role",
        "/_authenticated/acf/master/bank",
        "/_authenticated/acf/master/chart-of-account",
        "/_authenticated/acf/master/currency",
        "/_authenticated/acf/master/tax-code",
        "/_authenticated/adm/master/department",
        "/_authenticated/adm/master/employee",
        "/_authenticated/adm/master/item-category",
        "/_authenticated/adm/master/key-value",
        "/_authenticated/adm/master/menu",
        "/_authenticated/adm/master/reason",
        "/_authenticated/adm/master/role",
        "/_authenticated/adm/master/user",
        "/_authenticated/egd/master/process",
        "/_authenticated/egd/master/uom",
        "/_authenticated/mkt/master/billing-term",
        "/_authenticated/mnt/master/machine",
        "/_authenticated/pid/master/warehouse",
        "/_authenticated/prd/master/building",
        "/_authenticated/prd/master/fcs",
        "/_authenticated/prd/master/section",
        "/_authenticated/prd/master/sub-section",
        "/_authenticated/pur/master/billing-term",
        "/_authenticated/general/master/item/raw-material/group",
        "/_authenticated/general/master/item/raw-material/processing",
        "/_authenticated/general/master/item/raw-material/product",
        "/_authenticated/general/master/item/raw-material/sourcing",
        "/_authenticated/general/master/item/raw-material/surface-finishing"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/reset-password/$token": {
      "filePath": "reset-password.$token.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/adm/activity-log": {
      "filePath": "_authenticated/adm/activity-log.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/adm/approval-structure": {
      "filePath": "_authenticated/adm/approval-structure.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/adm/role-menu": {
      "filePath": "_authenticated/adm/role-menu.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/adm/role-permission": {
      "filePath": "_authenticated/adm/role-permission.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/adm/user-role": {
      "filePath": "_authenticated/adm/user-role.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/acf/master/bank": {
      "filePath": "_authenticated/acf/master/bank.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/acf/master/chart-of-account": {
      "filePath": "_authenticated/acf/master/chart-of-account.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/acf/master/currency": {
      "filePath": "_authenticated/acf/master/currency.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/acf/master/tax-code": {
      "filePath": "_authenticated/acf/master/tax-code.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/adm/master/department": {
      "filePath": "_authenticated/adm/master/department.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/adm/master/employee": {
      "filePath": "_authenticated/adm/master/employee.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/adm/master/item-category": {
      "filePath": "_authenticated/adm/master/item-category.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/adm/master/key-value": {
      "filePath": "_authenticated/adm/master/key-value.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/adm/master/menu": {
      "filePath": "_authenticated/adm/master/menu.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/adm/master/reason": {
      "filePath": "_authenticated/adm/master/reason.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/adm/master/role": {
      "filePath": "_authenticated/adm/master/role.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/adm/master/user": {
      "filePath": "_authenticated/adm/master/user.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/egd/master/process": {
      "filePath": "_authenticated/egd/master/process.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/egd/master/uom": {
      "filePath": "_authenticated/egd/master/uom.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/mkt/master/billing-term": {
      "filePath": "_authenticated/mkt/master/billing-term.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/mnt/master/machine": {
      "filePath": "_authenticated/mnt/master/machine.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/pid/master/warehouse": {
      "filePath": "_authenticated/pid/master/warehouse.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/prd/master/building": {
      "filePath": "_authenticated/prd/master/building.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/prd/master/fcs": {
      "filePath": "_authenticated/prd/master/fcs.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/prd/master/section": {
      "filePath": "_authenticated/prd/master/section.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/prd/master/sub-section": {
      "filePath": "_authenticated/prd/master/sub-section.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/pur/master/billing-term": {
      "filePath": "_authenticated/pur/master/billing-term.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/general/master/item/raw-material/group": {
      "filePath": "_authenticated/general/master/item/raw-material/group.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/general/master/item/raw-material/processing": {
      "filePath": "_authenticated/general/master/item/raw-material/processing.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/general/master/item/raw-material/product": {
      "filePath": "_authenticated/general/master/item/raw-material/product.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/general/master/item/raw-material/sourcing": {
      "filePath": "_authenticated/general/master/item/raw-material/sourcing.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/general/master/item/raw-material/surface-finishing": {
      "filePath": "_authenticated/general/master/item/raw-material/surface-finishing.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
